apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

secretGenerator:
- literals:
  - LDAP_ADDR=
  - LDAP_BINDDN=
  - LDAP_BINDCREDENTIALS=
  - LDAP_GROUP_SEARCHBASE=
  name: ldap-config
- literals:
  - GITLAB_URL=
  - GITLAB_TOKEN=
  name: gitlab-config
