---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.wellerman.bouchaud.org
  resources:
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.wellerman.bouchaud.org
  resources:
  - teams/finalizers
  verbs:
  - update
- apiGroups:
  - app.wellerman.bouchaud.org
  resources:
  - teams/status
  verbs:
  - get
  - patch
  - update
